language:   c
os:         linux
dist:       focal
#sudo:       false
compiler:
  - gcc
  - clang

#branches:
#  only:
#    - master
#    - debug

script:
  - cd src
  - make
  - ls -la pam2control.so
  - file pam2control.so
  - nm pam2control.so
  - ls -la p2ctl
  - file p2ctl
  - ./p2ctl help
  - ./p2ctl version
  - ./p2ctl search_path
  - nm p2ctl
