CC=     clang
LIBS=   -lpam
OBJ=    pam2control.o config.o log.o smtp.o

pam2control: ${OBJ}
	${CC} -Wall -fPIC -c pam2control.c config.c log.c smtp.c
	${CC} -shared -o pam2control.so ${OBJ} ${LIBS}


install:
	install -m 755 pam2control.so /usr/lib
	mkdir -p /etc/pam2control
	mkdir -p /var/log/pam2control
	mkdir -p /usr/share/man/man5/
	install -m 644 p2c.conf.5 /usr/share/man/man5/p2c.conf.5
	gzip -f /usr/share/man/man5/p2c.conf.5

.if exists(/etc/pam2control/p2c.conf)
	@echo "Config file is already exist"
.else
	install -m 600 p2c.conf.default /etc/pam2control/p2c.conf
.endif


clean:
	rm -f ${OBJ}


uninstall:
	rm -rf /etc/pam2control/
	rm -rf /usr/share/man/man5/p2c.conf.5.gz
	rm -rf /usr/lib/pam2control.so
