.TH "P2C\&.CONF" "5" "Apr 2020" "pam2control v0.1"
.SH NAME
p2c.conf \- \fBpam2control\fP configuration file.

.SH CONFIGURATION
To configure \fBpam2control\fP you will need to fill config file.
This file can contain the list of rules and also values for some variables.
.PP
Each rule has to include exactly four fields separated by spaces:
.RE 4
.PP
.RS 4
<SERVICE> <OPTION> <TARGET> <PARAMETERS>
.PP
SERVICE
.RS 4
defines \fIPAM\fR service that should be managed. List of PAM services could be found
in \fB/etc/pam.d/*\fP directory.
.PP
.RE
OPTION
.RS 4
behavior for its SERVICE. It could be one of two types: \fIOPEN\fR or \fICLOSE\fR.
.PP
.RE
TARGET
.RS 4
defines target for SERVICE. Supported targets are \fIUSER\fR and \fIGROUP\fR.
.PP
.RE
PARAMETERS
.RS 4
this field defines values for TARGET. It's possible to set list of parameters in one
line; use "," as a separator for that. No space is needed.
.PP

.RE
.RE
There are a list of variables that can be defined:
.PP
.RS 4
DEFAULT
.RS 4
It's posible to define default behavior for the not configured cases by using \fIDEFAULT\fR rule.
The syntax for this rule is defferent like for other rules. It's sepatated by ":" symbol,
doesn't contain spaces and accept only one of two values: 'CLOSE' or 'OPEN'. For example:
.PP
.RS 7
DEFAULT:CLOSE
.RE
.PP
This closes all not defined situations. In other words, everything what is not defined
in config file will be automatically interpreted as not allowed (i.e. should be ignored).
And vice versa: 'OPEN' will open access for all kind of connection, if there are no other
rules listed in config file which can be suitable for.
.br
If \fIDEFAULT\fR parameter will be not found in config file at all, default behavior will
be set to 'CLOSE'. It is highly recommended to set \fIDEFAULT\fR parameter in config file.
It makes it easier to debug the access problems if any and makes configuration more
intuitive.
.PP
.RE

LOGFILE
.RS 4
It's possible to set name of the logfile you like. Default value is
\fI/var/log/pam2control/p2c-<YEAR>-<MONTH>.log\fR. There is no need for logrotate, because
last symbols which includs current year and month "-<YEAR>-<MONTH>.log" will append automatically
to the end of filename (in other words, default filename is /var/log/pam2control/p2c).
.br
File permissions of logfiles are always 600 (read-write only for root).
Directory /var/log/pam2control/ is created during pam2control installation. If you would like
to use other directory, you will need to create it manually.
.br
For example, to become logfile /var/log/pam2control/mylogfile-2020-04.log use this line:
.PP
.RS 7
LOGFILE:/var/log/pam2control/mylogfile
.RE
.PP
In May (next month) pam2control will automatically create and start to use
/var/log/pam2control/mylogfile-2020-05.log. In June: ...2020-06.log, etc.
.RE

.PP
It can be helpfull to use comments in configuration file. Comments starts with the hash
character, #, and extend to the end of the physical line (exactly like for the most configuration
files in the UNIX/Linux world).
.PP
It's possible to switch \fBpam2control\fP to debug mode. By using this mode \fBpam2control\fP
writes more information to \fBsyslog\fP(3) what can be useful by debugging or development.
To switch pam2contol to debug mode, just add 'debug' to the end of p2c line in /etc/pam.d/<PAM>
file. This is the standard way to debug pam modules.
.PP

.SH AUTHOR
Written by Alexander Naumov <alexander_naumov@opensuse.org>
.PP
GitHub: https://github.com/alexander-naumov/pam2control

.SH "SEE ALSO"
.BR pam(3),
.BR pam(8),
.BR tty(4),
.BR login(1),
.BR utmp(5),
.BR group(5)
